server:
  port: 8080

spring:
  application:
    name: humuson

  docker:
    compose:
      file: 'docker-compose.yml'
      lifecycle-management: start_only

  data:
    mongodb:
      uri: mongodb://localhost:27017/logs